### ISSUE TITLE
High CPU usage from Postgres

### ISSUE THREAD

**Issue by filmaidykai** [YunoHost-Apps/peertube_ynh#143]
Hey just upgrade 2.0.0 to 2.1.0 and came a problem cpu working 100% maybe any solution how to fix it? because if cpu working all the power so and web page is down
![](https://i.imgur.com/UeAPVet.jpg)

**Comment by yalh76** [comment]
Have you checked at https://github.com/Chocobozzz/PeerTube ? Did someone else encounter that issue ?

**Comment by filmaidykai** [comment]
> Have you checked at https://github.com/Chocobozzz/PeerTube ? Did someone else encounter that issue ?

yea issue you can find here https://github.com/Chocobozzz/PeerTube/issues/2326

**Comment by yalh76** [comment]
Have you tested the different queries provided to see what is the issue ?

**Comment by dj92231** [comment]
Hello !
Same here.
Since the 2.0 the issue appeared but not so often.
Since the update to the 2.1 it's awful.
PostgreSQL has been optimized but no progress.
Many Select SQL requests are executed and never terminated.
CPU 100% just after launching Peertube and obviously Peertube very very slow ! :( :(
The slowest SQL request is : "Select channelid from video  AS...."
If any idea or if i can send you more details, thank you very much !

![image](https://user-images.githubusercontent.com/61296182/74982850-26d95a80-5435-11ea-9ff9-fe7d11bc18a4.png)

**Comment by yalh76** [comment]
> 
> 
> Hello !
> Same here.
> Since the 2.0 the issue appeared but not so often.
> Since the update to the 2.1 it's awful.
> PostgreSQL has been optimized but no progress.
> Many Select SQL requests are executed and never terminated.
> CPU 100% just after launching Peertube and obviously Peertube very very slow ! :( :(
> The slowest SQL request is : "Select channelid from video AS...."
> If any idea or if i can send you more details, thank you very much !
> 
> ![image](https://user-images.githubusercontent.com/61296182/74982850-26d95a80-5435-11ea-9ff9-fe7d11bc18a4.png)

maybe you should post that information at https://github.com/Chocobozzz/PeerTube/issues/2326 ?

**Comment by rigelk** [comment]
@yalh76, a fix was provided upstream in the issue you linked.

**Comment by yalh76** [comment]
> 
> 
> @yalh76, a fix was provided upstream in the issue you linked.

Yes, I've seen that, I'm also in the upstream issue. I propose we wait the next release, I think the patch will be included if other guys test it ^^
I can't, I don't use peertube ^^

**Comment by filmaidykai** [comment]
Alright how i can see they fix this problem in 2.1.1 version
