### ISSUE TITLE
Can't connect using admin password

### ISSUE THREAD

**Issue by mokas01** [YunoHost-Apps/peertube_ynh#19]
hi,

I tried to connect using my email adress and 'root' and the password given during the install : it failed
I tried to renew the admin password using the dedicated script in the terminal, using only 8 letters to be sure it wasn't a special caracter issue : it failed
I tried to use the "I forgot my password" on the webinterface : it failed.

The error message is always "Authentication failed." 
I have no log in /var/log/peertube/

My peertube isn't public (i.e behind SSO), if it matters 

**ynh version** :
yunohost: 
  repo: stable
  version: 2.7.10
yunohost-admin: 
  repo: stable
  version: 2.7.7
moulinette: 
  repo: stable
  version: 2.7.7
ssowat: 
  repo: stable
  version: 2.7.7

**Peertube version** : 
1.0.0-beta.3-2 (? last testing version of peertube_ynh)

**Comment by anmol26s** [comment]
The default login is root and the password is randomly generated now. Both the username(which is root) and the password generated comes to your email. There is no option for entering password while installation now. 
So are you using the username as root and the password which you got on your email?

In any case you can change your password by this command(assuming that you have only one instance of peertube running);
`$ cd /var/www/peertube && NODE_ENV=production npm run reset-password -- -u root
`
Now you can use the username as root and the new password you entered after running the command.

> My peertube isn't public (i.e behind SSO), if it matters

I have not tested it behind SSO, but it should work. 
In my opinion  why is the app need to be behind SSO ? The users can mark videos as private, further the admin can moderate the videos. Making the app behind SSO defeats its usefulness as all the social network like Mastadon,Diaspora,Hubzilla,Friendica should not be behind SSO so that other interface could connect to it.
Similarly videos on other instances which you have allowed are seen on your instance of peertube and your on others instance. Having peertube behind the SSO would hinder public flow of the video.
What are your thoughts on it?

**Comment by mokas01** [comment]
i still have the issue without sso. I noticed that the first error is "Unknown error" then "Authentication failed."

Are there logs somewhere ?

For info, the email sent after the install seem to be an issue when the admin email adress is on the same machine : 
> This is the mail system at host domain.tld.
>
> I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.
>
> For further assistance, please send mail to postmaster.
>
> If you do so, please include this problem report. You can
delete your own text from the attached returned message.
>
> The mail system
>
> <root@domain.tld>: mail for domain.tld loops back to myself

**Comment by anmol26s** [comment]
> Are there logs somewhere ?

Logs can be found in **/home/yunohost.app/peertube/storage/logs/peertube.log**

> For info, the email sent after the install seem to be an issue when the admin email adress is on the same machine 

Can you try with email other then the root like your_username@domain.tld ?

**Comment by anmol26s** [comment]
> you mean the email i gave for the install ? I tried it already without success

Can you try to change the password with command-line and check the logs again. Yes it would be good idea to check the set level to error and debug.

**Comment by mokas01** [comment]
i see nothing in the logs (set to debug) that could help : no error, no warning, only sql commands… ah and my yunohost username and password (readable) when i restart the service (but that is another issue)

I pasted the lines i got while executing the command in another terminal to change the pwd : 
https://paste.yunohost.org/dedoxozene.tex

**Comment by anmol26s** [comment]
Can you clear the browser cache and try?

**Comment by mokas01** [comment]
it keeps failing :/

**Comment by anmol26s** [comment]
Can you do ?

> cd /var/www/peertube && yarn install --production --pure-lockfile

and see if there are no errors.

**Comment by mokas01** [comment]
there is no error : 
> root@machine:/var/www/peertube# cd /var/www/peertube && yarn install --production --pure-lockfile
> yarn install v1.5.1
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> success Already up-to-date.
> $ cd client && yarn install --pure-lockfile
> yarn install v1.5.1
> [1/4] Resolving packages...
> success Already up-to-date.
> $ npm rebuild node-sass
> Done in 19.23s.
> Done in 37.88s.

**Comment by anmol26s** [comment]
> but after reloading the service, emptying the cache, and retrying, still not working.

Try a simple password like your_name and then try. Maybe some dependencies are unmet.

**Comment by anmol26s** [comment]
Try restarting nginx too. I remember one time when the peertube crashed restarting nginx worked.

**Comment by mokas01** [comment]
nginx restart worked \o/
