### ISSUE TITLE
When Upgrade to 4.1 - Prosody install breaks metronome XMPP service

### ISSUE THREAD

**Issue by madmaxlamenace** [YunoHost-Apps/peertube_ynh#311]
### Describe the bug
After an update of Peertube to 4.1 It seems the service XMPP metronome was crashed and it doesn't work anymore
### Context

- Hardware: *QEMU VM on proxmox x86 host
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: Peertube 4.1

### Steps to reproduce

Try to use your xmpp yunohost account on your default domain.tld 
The client says :
le serveur n'est pas responsable pour ce domaine yunohost

### Expected behavior

The client must say :
Connected

### Corrective action resolved the incident on metronome and XMPP yunohost service but not resolved the problem on prosody peertube

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo systemctl stop prosody
    sudo systemctl start metronome
    ```
The XMPP service works again, not tested the impact ion peertube when i desactivated prosody.

### Logs

nothing

**Comment by BDouze** [comment]
Prosody has been added for the live chat peertube plugin. And it does not need the prosody service to be running. the plugin is spawning its own prosody instance. 
Prosody should be installed with its service disabled

**Comment by madmaxlamenace** [comment]
After Peertube 4.1 upgrade the XMPP service doesn't work anymore.
For me it's an issue.
A program breaking another program when installed is a bug issue.

**Comment by BDouze** [comment]
I agree. I was only stating that peertube does not need the prosody service to be started. When the live chat plugin is spawning its own prosody process it does so using a different port than the one used by the service which does not conflict with metronome. 
More details in #278

**Comment by yalh76** [comment]
> I agree. I was only stating that peertube does not need the prosody service to be started. When the live chat plugin is spawning its own prosody process it does so using a different port than the one used by the service which does not conflict with metronome. More details in #278

Yes, but other package like jitsi need the prosody service started, so it was much easier to do it that way

**Comment by chbmeyer** [comment]
This is annoying.
I'm relying on XMPP for Yunohost and don't care whether it's metronome or prosody.

Since Peertube doesn't need the prosody service there is no reason to start it (and break metronome).
I don't care about Jitsie, too, but I need a working XMPP.

So I think
a) YNH should move completely to prosody (with disabled prosody till it works as default and metronome is dropped)
or
b) Jitsi should work with metronome (or metronome with Jitsi) without the need for prosody

But enabling prosody from Peertube (without the need to do so) because of Jitsi needing it is not right since it breaks Yunohost default config.

Of course I can disable prosody (as mentioned above), but then it re-enables itself after a while and my XMPP fails silently (or I get automatic diagnosis mails: "[ERROR] Service prosody is dead :("

So I agree: it "is a bug issue". Please fix it.

**Comment by yalh76** [comment]
> So I think a) YNH should move completely to prosody (with disabled prosody till it works as default and metronome is dropped)

There is no plan to move yunohost from metronome to prosody

> or b) Jitsi should work with metronome (or metronome with Jitsi) without the need for prosody

I've tryed during hours to make jitsi works with metronome. If you can do it, feels free to do a PR


> But enabling prosody from Peertube (without the need to do so) because of Jitsi needing it is not right since it breaks Yunohost default config.

If you think there is a better way to do it, feel free to do the required PRs for that. For example, installing the pluging live chat and prosody could be optional, etc ...

**Comment by eauchat** [comment]
Hello thank you all for this thread's requests and also answers of why the situation is as it is. It's nice to understand why suddenly prosody was appearing in the list of installed apps.  
From this I understand that if I'm not needing metronome, I can safely ignore the warning of the diagnosis that says that metronome has crashed.  
I have one question though, since peertube upgrade, the diagnosis tells me that `/etc/nsswitch.conf` has been manually modified. I was doing other upgrades at the same time, so I'm wondering if this happens because of the peertube update, and if I should ignore that warning.
This is the modification reported:
```
-hosts:          files myhostname dns
+hosts:          files myhostname mdns4_minimal [NOTFOUND=return] dns
```

**Comment by yalh76** [comment]
> Hello thank you all for this thread's requests and also answers of why the situation is as it is. It's nice to understand why suddenly prosody was appearing in the list of installed apps. From this I understand that if I'm not needing metronome, I can safely ignore the warning of the diagnosis that says that metronome has crashed. I have one question though, since peertube upgrade, the diagnosis tells me that `/etc/nsswitch.conf` has been manually modified. I was doing other upgrades at the same time, so I'm wondering if this happens because of the peertube update, and if I should ignore that warning. This is the modification reported:
> 
> ```
> -hosts:          files myhostname dns
> +hosts:          files myhostname mdns4_minimal [NOTFOUND=return] dns
> ```

as far as I know peertube_ynh upgrade doesn't modify `/etc/nsswitch.conf`

**Comment by csolisr** [comment]
Not sure if it's because of Jitsi and Peertube being installed concurrently, but I'm currently having issues making chat work with the latest Peertube. If I go to the peertube-plugin-livechat settings page, clicking the "List rooms" button gives an error saying "Room list failed", and launching the diagnostic gives an error code 400, "token is invalid". Is there a setting I'm missing on my side?

**Comment by csolisr** [comment]
Never mind the above, it seems to have been caused by dirty cache. I started a new session in a private tab and everything's working.

**Comment by tomdereub** [comment]
I'm still having this issue at each peertube upgrade. I don't need prosody, so each time I have to manually uninstall prosody. If I just stop prosody service and restart metronome, I get the issue again if the server reboots.
As proposed by @yalh76 , I think the better solution would be that installing the pluging live chat and prosody be optional. That said, I know it depends on volunteer's energy and time...
But I think it's worth re-opening this issue.

**Comment by madmaxlamenace** [comment]
you could try to disable the service using systemctl
systemctl disable prosody
I think this can solved the issue for the next upgrade.
