### ISSUE TITLE
Peertube need redis > 2.8.18 on Yunohost 2

### ISSUE THREAD

**Issue by nemsia** [YunoHost-Apps/peertube_ynh#54]
Hello,
The new peertube version need backport redis version on Jessie:
`"message": "Redis version needs to be greater than 2.8.18. Current: 2.8.17"`

Solved by:
`apt -t jessie-backports install redis-server`

**Comment by anmol26s** [comment]
Any reason for not updating to Stretch? I think its time to move on and only maintain the support for Stretch.

**Comment by frju365** [comment]
I agree with @anmol26s . The best is to move to Stretch definitely as it's totally stable today. If you do fix like that, the problem is that user won't understand the point to move to stretch and you will have to do jessie support. Many fix are include in Stretch version and more in Yunohost 3.0. It will cause problem of security anyway. So we may have to encourage ppl to move to stretch.

**Comment by yalh76** [comment]
Feel free to reopen this issue if needed.
